### ISSUE TITLE
USER STORY: Create Django Project

### ISSUE THREAD

**Issue by Indre-V** [Indre-V/teacup-tales-bookshop#13]
As a **developer**, I want to **install and add basic configurations to Django** so that **I can create a working application**.

## Acceptance Criteria
- [x] A virtual environment is created for the Django project.
- [x] Django is installed in the virtual environment.
- [x] A new Django project is created with the necessary files and directories.
- [x] The Django development server runs without any errors.
- [x] The Django project structure follows best practices.

## Tasks
- [x] Install Django
- [x] Create new project
- [x] Create app
- [x] Install packages 
- [x] Set up settings.py
