### ISSUE TITLE
 USER STORY: User Login and Logout Functionality

### ISSUE THREAD

**Issue by Indre-V** [Indre-V/teacup-tales-bookshop#15]
As a **customer**, I want to **be able to log in and out of my account** so that **I can use the platform**.

## Acceptance Criteria
- [ ] Users can access a login form.
- [x] Users can input their username and password.
- [x] Valid credentials allow users to log in successfully.
- [x] Invalid credentials display appropriate error messages.
- [x] Display option to log out.
- [ ] Display confirmation with username.

## Tasks
- [x] Implement backend authentication for user login.
- [ ] Verify user credentials and allow access upon successful login.
- [x] Set up error messages for invalid login attempts.
- [x] Set up confirmation of successful log out.
