### ISSUE TITLE
 USER STORY: Password Reset

### ISSUE THREAD

**Issue by Indre-V** [Indre-V/teacup-tales-bookshop#16]
As a **customer**, I want to **to be able to reset my password** so that **I do not loose access to my account**.

## Acceptance Criteria
- [x] Users can access a password reset form.
- [x] Users can reset their password using the provided instructions.

## Tasks
- [x] Create a password reset form with input fields.
- [ ] Allow users to reset their password using the provided instructions.
- [x] Test functionality with valid credentials
- [x] Test functionality with invalid credentials
