### ISSUE TITLE
USER STORY: Code Validation

### ISSUE THREAD

**Issue by Indre-V** [Indre-V/teacup-tales-bookshop#37]
As a **developer**, I want to **ensure that all syntax errors are identified and resolved during the code validation process** so that **the code is free from syntax-related issues**.

## Acceptance Criteria
- [x] Code is regularly checked using a syntax validator.
- [x] No syntax errors left in the submission.

## Tasks
- [x] Validate the code using HTML, CSS, JS and PEP8 validators
- [x] Address and fix any syntax errors identified by the validation tools.
