### ISSUE TITLE
USER STORY: Adopt Agile Methodology

### ISSUE THREAD

**Issue by Indre-V** [Indre-V/teacup-tales-bookshop#9]
As a **developer**, I want to **adopt Agile methodology** so that **I can deliver high quality product that meets the needs of the user.**

## Acceptance Criteria
- [x]  Understand the core principles and values of Agile methodology.
- [x] Effectively use Agile practices such as user stories, sprints, epics.

## Tasks
- [x] Establish a backlog of user stories that capture the requirements and priorities of the project.
- [ ] Break down user stories into smaller, manageable tasks that can be completed within a sprint.
- [x] Conduct sprint planning to determine which user stories and tasks will be included in each sprint.
